# Generated by Django 5.0.7 on 2024-07-27 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venda',
            old_name='data_hora',
            new_name='horario',
        ),
        migrations.AddField(
            model_name='venda',
            name='quantidade',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fruta',
            name='classificacao',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='fruta',
            name='fresca',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fruta',
            name='quantidade_disponivel',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='venda',
            name='desconto',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
